### ISSUE TITLE
grunt requiresafe now times out

### ISSUE THREAD

**Issue by plynchnlm** [requiresafe/grunt-requiresafe#7]
Two weeks ago I switched to using grunt-requiresafe (which I think has since been renamed grunt-nsp).  Today my tests are failing because of this problem from requiresafe:
(+) Error:  Client request error:  connect ETIMEDOUT

I saw the blog post about the merging of the projects.  You are not actually going to break the former requiresafe infrastructure, are you?  It seems like there should be some warning period to give people a chance to update.

**Comment by nlf** [comment]
we do intend to break the requiresafe infrastructure in favor of the nodesecurity infrastructure, yes. though we intend to have redirects in place that would ease the transition. it appears we have a bug in one of our configurations, which is why you're seeing the ETIMEDOUT. we'll get that corrected!

**Comment by plynchnlm** [comment]
I'm not sure what "get that corrected" means, but as of now (three days later), "grunt requiresafe" returns this:

(+) Error: Got an invalid response from requireSafe, please email the above debug output to support@requiresafe.com

**Comment by nlf** [comment]
unfortunately, since we retired the requiresafe infrastructure entirely, the error you see is all that's currently available. we have no intention of continuing to support anything that targets the old infrastructure.
